### ISSUE TITLE
Hackage version of the library fails

### ISSUE THREAD

**Issue by madgen** [ibabushkin/hapstone#1]
When trying to compile the version on Hackage I get the following:

```
    Configuring hapstone-0.2.0.1...
    Building hapstone-0.2.0.1...
    Preprocessing library hapstone-0.2.0.1...
    c2hs__bool_size.c:2:51: warning: format specifies type 'unsigned int' but the argument has type 'unsigned long' [-Wformat]
    int main(int argc, char *argv[]) { printf("%u\n", sizeof(_Bool)); return 0; }
                                               ~~     ^~~~~~~~~~~~~
                                               %lu
    1 warning generated.
    c2hs__bool_size.c:2:51: warning: format specifies type 'unsigned int' but the argument has type 'unsigned long' [-Wformat]
    int main(int argc, char *argv[]) { printf("%u\n", sizeof(_Bool)); return 0; }
                                               ~~     ^~~~~~~~~~~~~
                                               %lu
    1 warning generated.
    c2hs: Errors during expansion of binding hooks:

    src/Hapstone/Internal/Arm.chs:88: (column 27) [ERROR]  >>> Unknown member name!
      The structure has no member called `lshift'.  The structure is defined at
      ("/usr/local/include/capstone/arm.h": line 215).
    src/Hapstone/Internal/Arm.chs:82: (column 49) [ERROR]  >>> Unknown member name!
      The structure has no member called `lshift'.  The structure is defined at
      ("/usr/local/include/capstone/arm.h": line 215).
```

I don't think the warnings are important thought. The error does not seem to exist in Arm.chs anymore and I can compile HEAD from the repo clone just fine.

Also confusingly the version of HEAD from the cabal file is 1.0.1.0 while the latest version on Hackage is 0.2.0.1.

**Comment by ibabushkin** [comment]
The version on Hackage is the `next` branch here. It corresponds to the `next` branch of capstone and will be merged as soon as the new major release of capstone is there. That said, it is a moving target, so it seems some changes have been made that break the bindings. I will look into this as soon as possible, thanks for reporting it.

So from what I see at the moment, you have multiple options:
- use capstone from the `next` branch on git (this is what the devs seem to recommend in many cases and what bigger projects like `radare2` do)
- build version 0.1.0.1 from the `master` branch here. Sorry for the confusion.

**Comment by madgen** [comment]
I used the older version from Hackage, it compiles now. I'll let you know if I encounter other problems. Thank you!

**Comment by ibabushkin** [comment]
No Problem, closing this now.

**Comment by puffnfresh** [comment]
I'm getting this error with nixpkgs. The versions are capstone-3.0.5 and hapstone-0.2.0.1 - using hapstone-0.1.0.1 allows me to use the library.

I see Radare2 is using a particular commit of Capstone, I'll try to factor that out and change hapstone in nixpkgs to use that.
